_old_apps/vickrey_auction/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random


doc = """
In this Vickrey auction, 3 players bid for an object with private values. Each
player can only submit one bid.

See: Vickrey, William. "Counterspeculation, auctions, and competitive '
sealed tenders." The Journal of finance 16.1 (1961): 8-37.
"""


class Constants(BaseConstants):
    name_in_url = 'vickrey_auction'
    players_per_group = 3
    num_rounds = 1

    instructions_template = 'vickrey_auction/Instructions.html'

    endowment = c(100)


class Subsession(BaseSubsession):
    def creating_session(self):
        for p in self.get_players():
            p.private_value = random.randint(0, Constants.endowment)


class Group(BaseGroup):
    highest_bid = models.CurrencyField()
    second_highest_bid = models.CurrencyField()

    def set_payoffs(self):
        players = self.get_players()
        bids = sorted([p.bid_amount for p in players], reverse=True)
        self.highest_bid = bids[0]
        self.second_highest_bid = bids[1]
        players_with_highest_bid = [
            p for p in players
            if p.bid_amount == self.highest_bid
            ]
        # if tie, winner is chosen at random
        winner = random.choice(players_with_highest_bid)
        winner.is_winner = True
        for p in players:
            p.payoff = Constants.endowment
            if p.is_winner:
                p.payoff += (p.private_value - self.second_highest_bid)


class Player(BasePlayer):
    private_value = models.CurrencyField(
        doc="How much the player values the item, generated randomly"
    )

    bid_amount = models.CurrencyField(
        min=0, max=Constants.endowment,
        doc="Amount bidded by the player"
    )

    is_winner = models.BooleanField(
        initial=False,
        doc="""Indicates whether the player is the winner"""
    )

instructions/__init__.py
from otree.api import *

# Models #

class C(BaseConstants):
    NAME_IN_URL = 'instructions'
    PLAYERS_PER_GROUP = None
    NUM_ROUNDS = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    pay_id = models.StringField(label='PayID')

# Pages #

class InformedConsent(Page):
    pass

class PayID(Page):
    form_model = 'player'
    form_fields = ['pay_id']

page_sequence = [InformedConsent]

_old_apps/vickrey_auction/templates/vickrey_auction/Bid.html
{% extends "global/Page.html" %}
{% load otree %}

{% block title %}
    Bid
{% endblock %}

{% block styles %}
<link href="{% static "vickrey_auction/jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: 1.5em auto;
        width: 70%;
    }

    .bid {
        text-align: center;
    }

</style>
{% endblock %}


{% block content %}

    <p>
        The value of the object to you is <strong>{{ player.private_value }}</strong>.
        If you win the auction, you would have a payoff of
        <strong>{{ endowment_plus_private_value }} - second highest bid</strong>.
    </p>

    <div class="form-group required">
        <label class="control-label" for="id_bid_amount">
            Please submit a bid for the object (from 0 to {{ Constants.endowment }}):</label>
        <div class="controls">
            <input type="hidden" name="bid_amount" id="id_bid_amount" value="0">
            <div class="bid-slider"></div>
            <div class="bid">Your bid: <strong><span class="bid-value"></span></strong></div>
        </div>
    </div>

    {% next_button %}

    {% include Constants.instructions_template %}

{% endblock %}


{% block scripts %}
<script src="{% static "vickrey_auction/jquery-ui/jquery-ui.min.js" %}"></script>
<script>
jQuery(document).ready(function ($) {
    var input = $('#id_bid_amount');

    $('.bid-slider').slider({
        min: 0,
        max: {{ Constants.endowment|json }},
        slide: function (event, ui) {
            input.val(ui.value);
            updateBidValue();
        },
    });

    function updateBidValue() {
        $('.bid-value').text(input.val());
    }

    updateBidValue();
});
</script>
{% endblock %}

_old_apps/vickrey_auction/templates/vickrey_auction/Instructions.html
{% load otree %}

<div class="card bg-light instructions">
    <div class="card-body">

    <h3>
        Instructions
    </h3>

    <p>
        You have been randomly and anonymously matched with 2 other
        participants in an auction. Each of you is given {{ Constants.endowment }} to start.
    </p>
    <p>
        Before bidding, you will learn the value of the object to you.
        The value of the object differs from participant to participant and is
        randomly and independently drawn from 0 to {{ Constants.endowment }} for each participant.
    </p>
    <p>
        Next, you will privately submit a bid for the object.
        You can bid from 0 to {{ Constants.endowment }}.
        The participant with the highest bid wins the object and pays the second highest bid.
        In the event of a die, the winner will be chosen randomly
        will select the winner in the event of a tie bid and the winner will
        pay the highest bid other than her or his own bid.
    </p>
    <p>
        The payoff of the winner is calculated as<br/>
        <strong>
            Winner’s payoff = {{ Constants.endowment }} + Private value of the object to the winner - Second highest bid
        </strong><br/>
        The payoffs for others are the initial {{ Constants.endowment }}.
    </p>
    <p>
        For your convenience, these instructions will remain available to you on all subsequent screens of this study.
    </p>
    </div>
</div>

_old_apps/vickrey_auction/templates/vickrey_auction/Introduction.html
{% extends "global/Page.html" %}
{% load otree %}

{% block title %}
    Introduction
{% endblock %}

{% block content %}

    {% include Constants.instructions_template %}

    {% next_button %}

{% endblock %}

_old_apps/vickrey_auction/templates/vickrey_auction/Results.html
{% extends "global/Page.html" %}
{% load otree %}

{% block title %}
    Results
{% endblock %}

{% block content %}


    <p>
        {% if player.is_winner %}
            You won the auction!
        {% else %}
            You did not win the auction!
        {% endif %}
    </p>

    <table class="table">
        <tr>
            <th>Your value</th>
            <th>Your bid</th>
            <th>Winning bid</th>
            <th>Second-Highest Bid</th>
            <th>You Paid</th>
            <th>Your payoff</th>
        </tr>

        <tr>
            <td>{{ player.private_value }}</td>
            <td>{{ player.bid_amount }}</td>
            <td>{{ group.highest_bid }}</td>
            <td>{{ group.second_highest_bid }}</td>
            <td>
                {% if player.is_winner %}
                    {{ group.second_highest_bid }}
                {% else %}
                    0
                {% endif %}
            </td>
            <td>{{ player.payoff|floatformat:"-2" }}</td>
        </tr>

    </table>

    {% next_button %}

    {% include Constants.instructions_template %}

{% endblock %}